spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      database: ${SPRING_DATA_REDIS_DATABASE:0}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

app:
  seed-demo-data: false
  jwt:
    secret: ${APP_JWT_SECRET}
  redis:
    enabled: ${APP_REDIS_ENABLED:true}
  rabbitmq:
    enabled: ${APP_RABBITMQ_ENABLED:true}


