package com.linkvault.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    BAD_REQUEST,
    AUTH_INVALID_CREDENTIALS,
    AUTH_LOGIN_REQUIRED,
    AUTH_ACCESS_DENIED,
    USER_NOT_FOUND,
    VAULT_NOT_FOUND,
    VAULT_ACCESS_DENIED,
    FOLDER_NOT_FOUND,
    FOLDER_ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    RESOURCE_ACCESS_DENIED,
    TAG_NOT_FOUND,
    TAG_ACCESS_DENIED,
    STORAGE_UPLOAD_FAILED,
    INTERNAL_ERROR
}
